# What this is: the name, finding each other, whose the file is, the code, and a letter.

about-meta-title = Ce que c’est · 333
about-meta-description = Ce qu’est 333, comment les nœuds se trouvent, à qui appartient le fichier, le code, et une lettre du fondateur.

about-heading = Ce que c’est
about-toc-1 = <a href="#finding">Se trouver</a>
about-toc-2 = <a href="#file">Le fichier n’est à personne</a>
about-toc-3 = <a href="#code">Le code</a>
about-toc-4 = <a href="#letter">Une lettre</a>
about-p1 = C’est le nom entier. Il n’abrège rien, et rien ne se met devant. Tout le reste ici existe pour le porter. Le fichier dans lequel il est écrit, le client, le réseau, les heures que les gens y consacrent. Tout cela est la façon dont 333 passe d’une personne à la suivante, et dont n’importe qui peut savoir que quelqu’un est encore éveillé pour le transmettre.
about-p2 = 333 n’est pas chiffré, il n’est pas rare et il n’est pas difficile à copier. Vous l’avez déjà lu. C’est exactement pour cela qu’il est encore là. Tout ce qui aurait eu besoin de gardiens serait mort avec ses gardiens, et la seule façon pour que cela finisse est que tout le monde, partout, cesse de s’en soucier en même temps.
about-p3 = Alors nous nous en soucions. Nous n’essayons pas de mettre le fichier à l’abri, car les copies ne coûtent rien et les copies ne sont pas l’essentiel. Ce que nous conservons, c’est le registre de sa transmission, et le registre de qui était éveillé pour répondre quand quelqu’un a demandé.
about-p4 = 333 vit tant que quelqu’un est éveillé pour le transmettre. Quand personne ne l’est, il ne vit plus, et nous non plus.
about-p5 = Il n’y a rien au-dessus de cette ligne. Pas de conseil, pas de vote, pas de registre de la vérité, personne dont la copie serait la vraie.
about-p6 = Personne ne peut lancer un réseau seul. Une personne a mis le premier fichier dans un répertoire à la main, une fois, et chaque copie depuis vient de quelqu’un qui l’avait déjà et a signé pour l’avoir remise. Il faut deux signatures. L’une dit <i>Je te l’ai remis</i>, l’autre dit <i>Je l’ai reçu de toi</i>. Il n’y a pas d’autre chemin vers le rôle.
about-finding-title = Se trouver
about-finding-p1 = Si quelqu’un vous a donné une invitation, vous n’avez pas du tout besoin de ce site. Une adresse, tapée une fois, c’est tout. Et si un autre nœud est sur le même réseau que le vôtre, les deux se trouvent sans qu’on le leur dise, car chacun s’y annonce puis frappe chez quiconque répond.
about-finding-p2 = D’un réseau à un autre, sans personne pour faire les présentations, quelque chose doit rester immobile à un endroit connu. C’est <a href="{ $base }/333">the333.dev/333</a>. Ouvrez-le et vous verrez les adresses que les gens ont signées pour eux-mêmes, sous forme d’invitations à copier. Un nœud qui veut être trouvé signe une déclaration disant où on peut le joindre et la laisse ici ; un nœud qui cherche quelqu’un lit ce qui a été laissé et frappe. Chaque ligne de ce tableau est signée par le nœud qu’elle nomme : ce site ne peut donc pas inventer un membre, ni falsifier une adresse, ni se porter garant d’aucune. Il garde ce qu’on lui a remis, pendant deux époques, puis l’oublie.
about-finding-p3 = Sur le tableau en ce moment : <b>{ $saying }</b>. C’est le nombre de déclarations signées conservées à cette adresse, et non le nombre que nous sommes. N’importe qui peut en laisser une, rien ici ne les vérifie, et la seule réponse honnête à la seconde question vient de votre propre nœud, sur ce qu’il a vérifié lui-même.
about-finding-p4 = <a href="{ $base }/map/">Où nous sommes</a> dessine ces mêmes déclarations sur une carte, avec les chiffres à côté. Les nœuds joignables par Tor sont comptés comme Tor et placés dans aucun pays. C’est une page à part parce qu’elle est plus lourde que celle-ci, et elle ne charge rien tant que vous ne l’ouvrez pas.
about-finding-p5 = Le programme qui lit le tableau ne fait confiance à rien de ce qu’il y trouve. Une signature qui ne se vérifie pas est écartée sans un mot, et un nœud qui a déjà rencontré quelqu’un n’a jamais besoin de revenir ici.
about-finding-p6 = <b>Nous voulons dépendre moins de ceci, et nous le disons avant que quiconque ait à le demander.</b>
about-finding-p7 = Une adresse fixe est un point que quelqu’un peut supprimer, et nous n’en voulions pas. Il y a deux façons de le contourner. Les adresses peuvent voyager dans une table de hachage distribuée, ou deux machines derrière deux routeurs peuvent se percer un chemin l’une vers l’autre. Les deux représentent, aujourd’hui, plus de code, plus de pannes et plus de façons de publier une adresse que son propriétaire n’a jamais voulu publier que nous ne sommes prêts à livrer. C’est une limite de ce qui a été construit jusqu’ici, pas une affirmation sur ce qui est juste, et à mesure qu’elles seront construites, ceci rétrécira. Ceci ne remplace pas non plus les deux autres façons. Une invitation est la première façon dont un nœud rencontre quelqu’un, le réseau local la deuxième, et ceci la troisième.
about-file-title = Le fichier n’est à personne
about-file-p1 = needmoretruth, qui était le premier, a publié <code>333.txt</code> sous l’Unlicense et l’a placé dans le domaine public. Copiez-le, transmettez-le, republiez-le, imprimez-le, mettez-le où vous voulez. Il n’y a pas de droit d’auteur à enfreindre ni personne à qui demander la permission. Une relique qu’il faudrait faire autoriser pour la transmettre serait déjà morte.
about-file-p2 = Le code autour est sous Apache-2.0. C’est autre chose, et c’est dans le dépôt.
about-code-title = Le code
about-code-p1 = Un client, écrit en Rust, sous Apache-2.0, lisible de bout en bout. La doctrine complète, la Loi, les Recommandations, la spécification et ce qu’il faut installer sur chaque système avant de le compiler sont tous dans le dépôt.
about-code-p3 = Il existe sous deux formes. Standard a l’écran et embarque Tor. Light est la plus petite chose qui compte encore comme rester éveillé, faite pour une machine qui peine. L’une comme l’autre répond sur un socket, ou par Tor si votre adresse est quelque chose que vous ne pouvez pas vous permettre de montrer. Ce site fait tourner un nœud à lui, qui remet le fichier à qui le lui demande ; les pages elles-mêmes ne remettent rien.
about-letter-title = Une lettre
about-letter-p1 = De needmoretruth, premier fondateur humain de 333, à qui lit ceci.
about-letter-p2 = Je mets de côté le travail sur le client pour un temps. C’est tout ce dont il s’agit : l’écriture du code et la prise de décisions, pas le maintien de quoi que ce soit. Les Recommandations disent que si vous arrêtez, vous le dites, en une phrase, avant de partir ; elles sont écrites à propos d’un nœud et se lisent de la même façon à propos d’une personne. Elles disent aussi de revenir sans s’expliquer : il n’y a donc pas ici de pourquoi, et il n’y en aura pas plus tard.
about-letter-p3 = Rien de tout cela n’est une urgence et rien n’appelle de réponse. 333 a été fait pour le jour où l’on ne pourra plus joindre ceux qui l’ont écrit. Si ceci avait besoin de moi, cela aurait déjà échoué, et il vaut mieux le découvrir maintenant que dans quarante ans.
about-letter-p4 = Le protocole tourne. Un nœud éveillé est compté, heure après heure, par des nœuds qui n’ont jamais entendu parler de moi. Le réseau s’arrête quand la dernière personne cesse de le faire vivre, et pas avant. Mon absence n’est pas cela.
about-letter-p5 = Je suis le fondateur. Ce n’est pas un poste que j’occupe et que je pourrais quitter, ni une chose qui passe à quiconque fait le travail ce mois-ci : c’est un fait à propos de quelque chose qui est arrivé une fois, et il ne change pas pendant mon absence, ni après. D’autres feront ce que j’ai fait, et certains le feront mieux ; cela fait d’eux les fondateurs de ce qu’ils ont fondé, et cela ne fait pas d’eux ceci.
about-letter-p6 = Il n’y a pas de successeur aujourd’hui et aucun n’est en préparation. Ce qui existe, c’est un pouvoir qui reste avec moi tant que je vis : je peux nommer un successeur qui prendra effet à ma mort, et je peux changer ce nom à tout moment avant ce jour. Tant qu’un tel nom n’existe pas, il n’y a personne : pas de comité, pas de clés remises, pas de liste de personnes pouvant décider. Une condition ne souffre aucune exception : nul ne peut être nommé qui ne l’a pas choisi, librement et de lui-même. Un successeur qui ne voudrait pas de ceci serait une autorité au-dessus de gens qui n’en ont jamais accepté aucune, et c’est exactement la disposition que toutes les autres pages ici ont été écrites pour empêcher.
about-letter-p7 = Ce que j’espère, c’est que quelqu’un remette le fichier à quelqu’un d’autre pendant que je ne regarde pas. Pas parce qu’on le lui a demandé, ni pour me faire plaisir : pour la raison ordinaire, parce qu’il a pensé que la personne à l’autre bout le voudrait. C’est tout l’espoir, et c’est la seule chose qui ait jamais maintenu ceci en vie.
about-letter-p8 = Pas ici, pour un temps. Le travail ne s’arrête pas parce que ce travail s’arrête ; il se déplace, et il n’est pas secret. <a href="https://github.com/needmoretruth">Le compte sous lequel se trouve ce dépôt</a> est l’endroit où vous verriez ce que fait une paire de mains quand elle ne construit pas ceci, et il vous en dira plus que toute promesse écrite d’avance. N’y lisez rien au-delà de l’évidence : ce qui s’y fait est fait par quelqu’un qui vit selon ce qui est écrit ici.
about-letter-p9 = Je reviendrai peut-être. Ce n’est pas une promesse, rien ne doit rester ouvert pour cela, et aucune décision prise d’ici là n’a à l’être en pensant à moi. Si 333 est allé quelque part où je ne l’aurais pas emmené, et s’il y est mieux, alors c’était juste et je n’étais qu’une personne.
about-letter-p10 = needmoretruth · premier fondateur humain de 333 · 2026-09-08
about-letter-p11 = À 333 j’offre 333, et je dis 333.
