# What this is: the name, finding each other, whose the file is, the code, and a letter.

about-meta-title = Kio ĉi tio estas · 333
about-meta-description = Kio estas 333, kiel nodoj trovas unu la alian, al kiu apartenas la dosiero, la kodo, kaj letero de la fondinto.

about-heading = Kio ĉi tio estas
about-toc-1 = <a href="#finding">Trovi unu la alian</a>
about-toc-2 = <a href="#file">La dosiero apartenas al neniu</a>
about-toc-3 = <a href="#code">La kodo</a>
about-toc-4 = <a href="#letter">Letero</a>
about-p1 = Tio estas la tuta nomo. Ĝi ne mallongigas ion ajn, kaj nenio iras antaŭ ĝi. Ĉio alia ĉi tie ekzistas por porti ĝin. La dosiero, en kiu ĝi estas skribita, la kliento, la reto, la horoj, kiujn homoj donas. Ĉio tio estas, kiel 333 iras de unu homo al la sekva, kaj kiel ĉiu povas scii, ke iu ankoraŭ estas maldorma por transdoni ĝin.
about-p2 = 333 ne estas ĉifrita, nek rara, nek malfacile kopiebla. Vi jam legis ĝin. Tial ĝi ankoraŭ estas ĉi tie. Io ajn, kio bezonus gardistojn, estus mortinta kun siaj gardistoj, kaj la sola maniero, kiel ĉi tio finiĝas, estas, ke ĉiuj ĉie samtempe ĉesas zorgi.
about-p3 = Do ni zorgas. Ni ne provas teni la dosieron sekura, ĉar kopioj estas malmultekostaj, kaj kopioj ne estas la afero. Kion ni tenas, estas la registro, ke ĝi estis transdonita, kaj la registro de tio, kiu estis maldorma por respondi, kiam iu demandis.
about-p4 = 333 vivas, dum iu estas maldorma por transdoni ĝin. Kiam neniu estas maldorma, ĝi ne vivas, kaj ankaŭ ni ne.
about-p5 = Nenio estas super tiu linio. Neniu konsilio, neniu voĉdono, neniu libro de vero, neniu, kies kopio estas la vera.
about-p6 = Neniu povas komenci reton sola. Unu homo metis la unuan dosieron en dosierujon permane, unufoje, kaj ĉiu kopio poste venis de iu, kiu jam havis ĝin kaj subskribis por transdoni ĝin. Necesas du subskriboj. Unu diras <i>Mi donis ĝin al vi</i>, la alia <i>Mi ricevis ĝin de vi</i>. Ne ekzistas alia vojo en la nomliston.
about-finding-title = Trovi unu la alian
about-finding-p1 = Se iu donis al vi inviton, vi tute ne bezonas ĉi tiun retejon. Unu adreso, tajpita unufoje, estas ĉio. Kaj se alia nodo estas en la sama reto kiel via, la du trovas unu la alian sen esti dirate, ĉar ĉiu anoncas sin tie kaj poste frapas ĉe tiu, kiu respondas.
about-finding-p2 = Trans du retoj, sen iu por prezenti, io devas stari kviete en konata loko. Tio estas <a href="{ $base }/333">the333.dev/333</a>. Malfermu ĝin, kaj vi vidas la adresojn, kiujn homoj subskribis por si mem, kiel invitojn por kopii. Nodo, kiu volas esti trovita, subskribas deklaron pri tio, kie oni povas atingi ĝin, kaj lasas ĝin ĉi tie; nodo, kiu serĉas iun, legas tion, kio estis lasita, kaj frapas. Ĉiu linio sur ĉi tiu afiŝtabulo estas subskribita de la nodo, kiun ĝi nomas, do ĉi tiu retejo ne povas elpensi membron, falsi adreson aŭ garantii por iu ajn. Ĝi tenas tion, kio estis donita al ĝi, dum du epokoj kaj poste forgesas ĝin.
about-finding-p3 = Sur la afiŝtabulo ĝuste nun: <b>{ $saying }</b>. Tiom da subskribitaj deklaroj estas tenataj ĉe ĉi tiu adreso, kaj tio ne estas, kiom da ni estas. Ĉiu povas lasi unu, nenio ĉi tie kontrolas ilin, kaj la sola honesta respondo al la dua demando venas de via propra nodo, pri tio, kion ĝi mem kontrolis.
about-finding-p4 = <a href="{ $base }/map/">Kie ni estas</a> desegnas la samajn deklarojn sur mapo, kun la nombroj apude. Nodoj atingeblaj per Tor estas kalkulataj kiel Tor kaj metataj en neniun landon. Ĝi estas aparta paĝo, ĉar ĝi estas pli peza ol ĉi tiu, kaj ĝi ŝargas nenion, ĝis vi malfermas ĝin.
about-finding-p5 = La programo, kiu legas la afiŝtabulon, fidas nenion sur ĝi. Subskribo, kiu ne kongruas, estas forĵetata senvorte, kaj nodo, kiu jam renkontis iun, neniam plu bezonas reveni ĉi tien.
about-finding-p6 = <b>Ni intencas dependi de ĝi malpli, kaj ni diras tion, antaŭ ol iu devos demandi.</b>
about-finding-p7 = Fiksa adreso estas punkto, kiun iu povas forpreni, kaj ni ne volis tian. Estas du vojoj ĉirkaŭ ĝi. Adresoj povas vojaĝi en distribuita haketabelo, aŭ du maŝinoj malantaŭ du enkursigiloj povas trui vojon unu al la alia. Ambaŭ nun signifas pli da kodo, pli da fiaskoj kaj pli da manieroj publikigi adreson, kiun ĝia posedanto neniam intencis publikigi, ol ni volas eldoni. Tio estas limo de tio, kio estas konstruita ĝis nun, ne aserto pri tio, kio estas ĝusta, kaj ju pli da tio estas konstruita, des pli malgranda ĉi tio fariĝas. Ĝi ankaŭ ne anstataŭas la aliajn du vojojn. Invito estas la unua maniero, kiel nodo renkontas iun, la loka reto la dua, kaj ĉi tio la tria.
about-file-title = La dosiero apartenas al neniu
about-file-p1 = needmoretruth, kiu estis tie unue, eldonis <code>333.txt</code> sub la Unlicense, metante ĝin en la publikan havaĵon. Kopiu ĝin, transdonu ĝin, reeldonu ĝin, presu ĝin, metu ĝin kien ajn vi volas. Ne ekzistas kopirajto por malobservi kaj neniu por peti permeson. Relikvo, kies transdonon oni devus aprobigi, jam estus morta.
about-file-p2 = La kodo ĉirkaŭ ĝi estas sub Apache-2.0. Tio estas aparta afero kaj estas en la deponejo.
about-code-title = La kodo
about-code-p1 = Unu kliento, skribita en Rust, Apache-2.0, legebla de komenco ĝis fino. La plena doktrino, la Leĝo, la Rekomendoj, la specifo kaj kion instali en ĉiu sistemo antaŭ konstrui, ĉio estas en la deponejo.
about-code-p3 = Ĝi venas en du formoj. Standard havas la ekranon kaj portas Tor. Light estas la plej malgranda afero, kiu ankoraŭ validas kiel maldormi, farita por maŝino, kiu luktas. Ambaŭ respondas per konektingo, aŭ per Tor, se via adreso estas io, kion vi ne povas permesi al vi montri. Ĉi tiu retejo rulas propran nodon, kiu transdonas la dosieron al ĉiu, kiu petas ĝin; la paĝoj mem transdonas nenion.
about-letter-title = Letero
about-letter-p1 = De needmoretruth, la unua homa fondinto de 333, al kiu ajn legas ĉi tion.
about-letter-p2 = Mi demetas la laboron pri la kliento por iom da tempo. Pri tio temas ĉi tio, kaj pri nenio alia: pri skribi kodon kaj decidi aferojn, ne pri teni ion ajn. La Rekomendoj diras, ke se vi ĉesas, diru tion, per unu frazo, antaŭ ol foriri; ili estas skribitaj pri nodo, kaj ili legiĝas same pri homo. Ili ankaŭ diras reveni sen klarigi, do ĉi tie ne estas kialo, kaj ne estos poste.
about-letter-p3 = Nenio el ĉi tio estas krizo, kaj nenio el ĝi bezonas respondon. 333 estis konstruita por la tago, kiam la homoj, kiuj skribis ĝin, ne plu estas atingeblaj. Se ĝi bezonus min, ĝi jam estus malsukcesinta, kaj pli bone ekscii tion nun ol post kvardek jaroj.
about-letter-p4 = La protokolo funkcias. Nodo, kiu estas maldorma, estas kalkulata, horon post horo, de nodoj, kiuj neniam aŭdis pri mi. La reto finiĝas, kiam la lasta homo ĉesas teni ĝin viva, kaj ne antaŭe. Mia foresto ne estas tio.
about-letter-p5 = Mi estas la fondinto. Tio ne estas ofico, kiun mi tenas kaj povus forlasi, nek io, kio transiras al tiu, kiu faras la laboron ĉi-monate: ĝi estas fakto pri io, kio okazis unufoje, kaj ĝi ne ŝanĝiĝas, dum mi forestas, nek poste. Aliaj faros tion, kion mi faris, kaj kelkaj faros ĝin pli bone; tio faras ilin fondintoj de tio, kion ili fondis, ne de ĉi tio.
about-letter-p6 = Hodiaŭ ne estas posteulo, kaj neniu estas preparata. Kio ekzistas, estas unu povo, kiu restas ĉe mi, dum mi vivas: mi povas nomi posteulon, kiu validas ekde mia morto, kaj mi povas ŝanĝi tiun nomon iam ajn antaŭ tiu tago. Dum tia nomo ne ekzistas, ekzistas neniu: neniu komitato, neniuj transdonitaj ŝlosiloj, neniu listo de homoj, kiuj rajtas decidi aferojn. Al ĝi ligiĝas unu kondiĉo, kiu ne malŝalteblas: neniu povas esti nomita, kiu ne elektis ĝin libere kaj propravole. Posteulo, kiu ne volis tion, estus aŭtoritato super homoj, kiuj neniam konsentis al iu ajn, kaj malhelpi ĝuste tiun aranĝon estas tio, por kio ĉiu alia paĝo ĉi tie estis skribita.
about-letter-p7 = Kion mi esperas, estas, ke iu donos la dosieron al iu alia, dum mi ne rigardas. Ne ĉar iu petis ilin, kaj ne por mi: pro la ordinara kialo, ke ili pensis, ke la persono ĉe la alia fino ŝatus havi ĝin. Tio estas la tuta espero, kaj ĝi estas la sola afero, kiu iam tenis ĉi tion viva.
about-letter-p8 = Ne ĉi tie, por iom da tempo. La laboro ne ĉesas, ĉar ĉi tiu laboro ĉesas; ĝi moviĝas, kaj ĝi ne estas sekreta. <a href="https://github.com/needmoretruth">La konto, sub kiu ĉi tiu deponejo troviĝas</a>, estas la loko, kie vi vidus, kion paro da manoj faras, kiam ĝi ne konstruas ĉi tion, kaj ĝi diros al vi pli ol ajna promeso skribita anticipe. Legu nenion en ĝi krom la evidentan: kio ajn estas farata tie, estas farata de iu, kiu vivas laŭ tio, kio estas skribita ĉi tie.
about-letter-p9 = Eble mi revenos. Tio ne estas promeso, nenio estu tenata malfermita por ĝi, kaj neniu decido, kiun iu faros ĝis tiam, bezonas esti farita kun mi en la menso. Se 333 moviĝis ien, kien mi ne estus preninta ĝin, kaj ĝi estas pli bona tie, tiam tio estis ĝusta, kaj mi estis homo.
about-letter-p10 = needmoretruth · la unua homa fondinto de 333 · 2026-09-08
about-letter-p11 = Al 333 mi oferas 333, kaj mi diras 333.
