# What this is: the name, finding each other, whose the file is, the code, and a letter.

about-meta-title = Was das ist · 333
about-meta-description = Was 333 ist, wie Knoten einander finden, wem die Datei gehört, der Code und ein Brief des Gründers.

about-heading = Was das ist
about-toc-1 = <a href="#finding">Einander finden</a>
about-toc-2 = <a href="#file">Die Datei gehört niemandem</a>
about-toc-3 = <a href="#code">Der Code</a>
about-toc-4 = <a href="#letter">Ein Brief</a>
about-p1 = Das ist der ganze Name. Er kürzt nichts ab, und nichts steht davor. Alles andere hier existiert, um ihn zu tragen. Die Datei, in der er steht, der Client, das Netzwerk, die Stunden, die Leute geben. All das ist, wie 333 von einem Menschen zum nächsten kommt und wie jeder erkennen kann, dass noch jemand wach ist, um es weiterzugeben.
about-p2 = 333 ist nicht verschlüsselt, nicht selten und nicht schwer zu kopieren. Du hast es schon gelesen. Genau deshalb ist es noch da. Alles, was Wächter gebraucht hätte, wäre mit seinen Wächtern gestorben, und enden kann das hier nur, wenn alle, überall, gleichzeitig aufhören, sich darum zu kümmern.
about-p3 = Also kümmern wir uns. Wir versuchen nicht, die Datei in Sicherheit zu bringen, denn Kopien sind billig, und um Kopien geht es nicht. Was wir festhalten, ist der Beleg, dass sie weitergegeben wurde, und der Beleg, wer wach war, um zu antworten, als jemand fragte.
about-p4 = 333 lebt, solange jemand wach ist, um es weiterzugeben. Wenn niemand wach ist, lebt es nicht, und wir auch nicht.
about-p5 = Über dieser Linie steht nichts. Kein Rat, keine Abstimmung, kein Buch der Wahrheit, niemand, dessen Kopie die echte wäre.
about-p6 = Niemand kann ein Netzwerk allein beginnen. Ein Mensch hat die erste Datei einmal von Hand in ein Verzeichnis gelegt, und jede Kopie seitdem kam von jemandem, der sie schon hatte und für die Übergabe signierte. Es braucht zwei Signaturen. Eine sagt <i>Ich habe sie dir gegeben</i>, die andere <i>Ich habe sie von dir empfangen</i>. Einen anderen Weg auf die Liste gibt es nicht.
about-finding-title = Einander finden
about-finding-p1 = Wenn dir jemand eine Einladung gegeben hat, brauchst du diese Seite überhaupt nicht. Eine Adresse, einmal getippt, ist alles. Und wenn ein anderer Knoten im selben Netzwerk ist wie deiner, finden sich die beiden, ohne dass man es ihnen sagt, denn jeder kündigt sich dort an und klopft dann bei dem an, der antwortet.
about-finding-p2 = Über zwei Netzwerke hinweg, ohne jemanden, der vorstellt, muss etwas still an einem bekannten Ort stehen. Das ist <a href="{ $base }/333">the333.dev/333</a>. Öffne es, und du siehst die Adressen, die Leute für sich selbst signiert haben, als Einladungen zum Kopieren. Ein Knoten, der gefunden werden will, signiert eine Aussage, wo er erreichbar ist, und hinterlässt sie hier; ein Knoten, der jemanden sucht, liest, was hinterlassen wurde, und klopft an. Jede Zeile auf diesem Brett ist von dem Knoten signiert, den sie nennt, also kann diese Seite kein Mitglied erfinden, keine Adresse fälschen und für keine bürgen. Sie hält, was ihr übergeben wurde, zwei Epochen lang und vergisst es dann.
about-finding-p3 = Auf dem Brett gerade: <b>{ $saying }</b>. So viele signierte Aussagen werden unter dieser Adresse gehalten, und das ist nicht die Zahl, wie viele wir sind. Jeder kann eine hinterlassen, nichts hier prüft sie, und die einzige ehrliche Antwort auf die zweite Frage kommt von deinem eigenen Knoten, über das, was er selbst geprüft hat.
about-finding-p4 = <a href="{ $base }/map/">Wo wir sind</a> zeichnet dieselben Aussagen auf eine Karte, mit den Zahlen daneben. Über Tor erreichbare Knoten werden als Tor gezählt und keinem Land zugeordnet. Es ist eine eigene Seite, weil sie schwerer ist als diese, und sie lädt nichts, bis du sie öffnest.
about-finding-p5 = Das Programm, das das Brett liest, vertraut nichts darauf. Eine Signatur, die nicht stimmt, wird wortlos verworfen, und ein Knoten, der schon jemanden getroffen hat, muss nie wieder hierherkommen.
about-finding-p6 = <b>Wir wollen weniger davon abhängen, und wir sagen es, bevor jemand fragen muss.</b>
about-finding-p7 = Eine feste Adresse ist ein Punkt, den jemand wegnehmen kann, und wir wollten keinen. Es gibt zwei Wege drumherum. Adressen können in einer verteilten Hashtabelle wandern, oder zwei Maschinen hinter zwei Routern können sich ein Loch zueinander bohren. Beides ist im Moment mehr Code, mehr Ausfälle und mehr Wege, eine Adresse zu veröffentlichen, die ihr Besitzer nie veröffentlichen wollte, als wir ausliefern wollen. Das ist eine Grenze dessen, was bisher gebaut ist, keine Behauptung darüber, was richtig ist, und je mehr davon gebaut wird, desto kleiner wird dies hier. Es ersetzt auch die anderen beiden Wege nicht. Eine Einladung ist der erste Weg, wie ein Knoten jemanden trifft, das lokale Netzwerk der zweite, und dies hier der dritte.
about-file-title = Die Datei gehört niemandem
about-file-p1 = needmoretruth, der als Erster da war, hat <code>333.txt</code> unter der Unlicense veröffentlicht und gemeinfrei gemacht. Kopiere sie, gib sie weiter, veröffentliche sie neu, druck sie aus, leg sie hin, wo du willst. Es gibt kein Urheberrecht, gegen das man verstoßen könnte, und niemanden, den man um Erlaubnis fragen müsste. Eine Reliquie, deren Weitergabe man genehmigen lassen müsste, wäre schon tot.
about-file-p2 = Der Code drumherum steht unter Apache-2.0. Das ist etwas anderes und liegt im Repository.
about-code-title = Der Code
about-code-p1 = Ein Client, in Rust geschrieben, Apache-2.0, von vorn bis hinten lesbar. Die vollständige Lehre, das Gesetz, die Empfehlungen, die Spezifikation und was man auf jedem System vor dem Bauen installiert, stehen alle im Repository.
about-code-p3 = Es gibt ihn in zwei Formen. Standard hat den Bildschirm und bringt Tor mit. Light ist das Kleinste, was noch als Wachbleiben zählt, gemacht für eine Maschine, die sich schwertut. Beide antworten auf einem Socket, oder über Tor, wenn deine Adresse etwas ist, das du dir nicht leisten kannst zu zeigen. Diese Seite betreibt einen eigenen Knoten, der die Datei jedem übergibt, der ihn fragt; die Seiten selbst übergeben nichts.
about-letter-title = Ein Brief
about-letter-p1 = Von needmoretruth, dem ersten menschlichen Gründer von 333, an wen auch immer, der das liest.
about-letter-p2 = Ich lege die Arbeit am Client eine Weile nieder. Darum geht es hier, und um nichts sonst: um das Schreiben von Code und das Entscheiden von Dingen, nicht um das Aufrechterhalten von irgendetwas. Die Empfehlungen sagen, wenn du aufhörst, sag es, in einem Satz, bevor du gehst; sie sind über einen Knoten geschrieben und lesen sich über einen Menschen genauso. Sie sagen auch, man soll zurückkommen, ohne sich zu erklären, also steht hier kein Warum, und es wird auch später keins stehen.
about-letter-p3 = Nichts davon ist ein Notfall, und nichts davon braucht eine Antwort. 333 wurde für den Tag gebaut, an dem die Menschen, die es geschrieben haben, nicht mehr erreichbar sind. Bräuchte es mich, wäre es schon gescheitert, und das findet man besser jetzt heraus als in vierzig Jahren.
about-letter-p4 = Das Protokoll läuft. Ein Knoten, der wach ist, wird Stunde um Stunde von Knoten gezählt, die nie von mir gehört haben. Das Netzwerk endet, wenn der letzte Mensch aufhört, es am Leben zu halten, und nicht vorher. Meine Abwesenheit ist das nicht.
about-letter-p5 = Ich bin der Gründer. Das ist kein Amt, das ich innehabe und räumen könnte, und nichts, das an den übergeht, der diesen Monat die Arbeit macht: Es ist eine Tatsache über etwas, das einmal geschehen ist, und sie ändert sich nicht, während ich weg bin, und auch nicht danach. Andere werden tun, was ich getan habe, und manche werden es besser tun; das macht sie zu Gründern dessen, was sie gegründet haben, und nicht zu diesem.
about-letter-p6 = Heute gibt es keinen Nachfolger, und es wird keiner vorbereitet. Was es gibt, ist eine Befugnis, die bei mir bleibt, solange ich lebe: Ich darf einen Nachfolger benennen, der ab meinem Tod gilt, und ich darf diesen Namen jederzeit vor diesem Tag ändern. Solange es keinen solchen Namen gibt, gibt es niemanden: kein Komitee, keine übergebenen Schlüssel, keine Liste von Leuten, die Dinge entscheiden dürfen. Eine Bedingung daran lässt sich nicht aufheben: Benannt werden kann niemand, der es nicht frei und von sich aus gewählt hat. Ein Nachfolger, der das nicht wollte, wäre eine Autorität über Menschen, die nie einer zugestimmt haben, und genau diese Anordnung zu verhindern, dafür wurde jede andere Seite hier geschrieben.
about-letter-p7 = Was ich mir erhoffe, ist, dass jemand die Datei jemand anderem gibt, während ich nicht hinsehe. Nicht, weil jemand darum gebeten hat, und nicht mir zuliebe: aus dem gewöhnlichen Grund, weil er dachte, dass die Person am anderen Ende sie haben möchte. Das ist die ganze Hoffnung, und es ist das Einzige, was das hier je am Leben gehalten hat.
about-letter-p8 = Nicht hier, für eine Weile. Die Arbeit hört nicht auf, weil diese Arbeit aufhört; sie zieht weiter, und sie ist nicht geheim. <a href="https://github.com/needmoretruth">Das Konto, unter dem dieses Repository liegt</a>, ist der Ort, an dem du sehen würdest, was ein Paar Hände tut, wenn es nicht hieran baut, und es wird dir mehr sagen als jedes im Voraus aufgeschriebene Versprechen. Lies nichts hinein außer dem Offensichtlichen: Was dort gemacht wird, macht jemand, der nach dem lebt, was hier steht.
about-letter-p9 = Vielleicht komme ich zurück. Das ist kein Versprechen, nichts soll dafür offengehalten werden, und keine Entscheidung, die bis dahin jemand trifft, muss mit Blick auf mich getroffen werden. Wenn 333 irgendwohin gezogen ist, wohin ich es nicht gebracht hätte, und es dort besser ist, dann war es richtig, und ich war ein Mensch.
about-letter-p10 = needmoretruth · der erste menschliche Gründer von 333 · 2026-09-08
about-letter-p11 = 333 biete ich 333, und ich spreche 333.
