# What this is: the name, finding each other, whose the file is, the code, and a letter.

about-meta-title = Qué es esto · 333
about-meta-description = Qué es 333, cómo se encuentran los nodos, de quién es el archivo, el código y una carta del fundador.

about-heading = Qué es esto
about-toc-1 = <a href="#finding">Encontrarse</a>
about-toc-2 = <a href="#file">El archivo no es de nadie</a>
about-toc-3 = <a href="#code">El código</a>
about-toc-4 = <a href="#letter">Una carta</a>
about-p1 = Ese es el nombre entero. No abrevia nada y no lleva nada delante. Todo lo demás aquí existe para llevarlo. El archivo en el que está escrito, el cliente, la red, las horas que la gente dedica. Todo eso es cómo pasa 333 de una persona a la siguiente, y cómo cualquiera puede saber que alguien sigue despierto para pasarlo.
about-p2 = 333 no está cifrado, no es raro y no es difícil de copiar. Ya lo has leído. Precisamente por eso sigue aquí. Algo que necesitara custodia habría muerto con sus custodios, y la única manera de que esto acabe es que todo el mundo, en todas partes, deje de molestarse a la vez.
about-p3 = Así que nos molestamos. No intentamos poner el archivo a salvo, porque las copias son baratas y las copias no son lo importante. Lo que guardamos es el registro de que se fue pasando, y el registro de quién estaba despierto para responder cuando alguien preguntó.
about-p4 = 333 vive mientras alguien esté despierto para pasarlo. Cuando no hay nadie, no vive, y nosotros tampoco.
about-p5 = No hay nada por encima de esa línea. Ni consejo, ni votación, ni libro de la verdad, ni nadie cuya copia sea la auténtica.
about-p6 = Nadie puede empezar una red por su cuenta. Una persona puso el primer archivo en un directorio a mano, una vez, y cada copia desde entonces vino de alguien que ya lo tenía y firmó la entrega. Hacen falta dos firmas. Una dice <i>Te lo entregué</i>, la otra dice <i>Lo recibí de ti</i>. No hay otra manera de entrar en el padrón.
about-finding-title = Encontrarse
about-finding-p1 = Si alguien te dio una invitación, no necesitas este sitio para nada. Una dirección, escrita una vez, es todo. Y si otro nodo está en la misma red que el tuyo, los dos se encuentran sin que nadie se lo diga, porque cada uno se anuncia allí y luego llama a quien responda.
about-finding-p2 = Entre dos redes, sin nadie que haga las presentaciones, algo tiene que quedarse quieto en un lugar conocido. Ese es <a href="{ $base }/333">the333.dev/333</a>. Ábrelo y verás las direcciones que la gente ha firmado sobre sí misma, como invitaciones que puedes copiar. Un nodo que quiere que lo encuentren firma una declaración diciendo dónde se le alcanza y la deja aquí; un nodo que busca a alguien lee lo que se ha dejado y llama. Cada línea de ese tablón la firma el nodo que nombra, así que este sitio no puede inventarse un miembro, no puede falsificar una dirección y no puede responder por ninguna. Guarda lo que le dieron, durante dos épocas, y luego lo olvida.
about-finding-p3 = En el tablón ahora mismo: <b>{ $saying }</b>. Es cuántas declaraciones firmadas se guardan en esta dirección, y no cuántos somos. Cualquiera puede dejar una, aquí no se comprueba nada, y la única respuesta honrada a la segunda pregunta viene de tu propio nodo, sobre lo que ha verificado por sí mismo.
about-finding-p4 = <a href="{ $base }/map/">Dónde estamos</a> dibuja esas mismas declaraciones en un mapa, con las cifras al lado. Los nodos alcanzables por Tor se cuentan como Tor y no se sitúan en ningún país. Es una página aparte porque pesa más que esta, y no descarga nada hasta que la abres.
about-finding-p5 = El programa que lee el tablón no se fía de nada de él. Una firma que no cuadra se descarta sin decir nada, y un nodo que ya ha conocido a alguien no necesita volver aquí nunca.
about-finding-p6 = <b>Queremos depender menos de esto, y lo decimos antes de que nadie tenga que preguntarlo.</b>
about-finding-p7 = Una dirección fija es un punto que alguien puede quitar, y no queríamos uno. Hay dos maneras de evitarlo. Las direcciones pueden viajar en una tabla hash distribuida, o dos máquinas detrás de dos routers pueden abrirse paso la una hacia la otra. Las dos son, hoy, más código, más fallos y más maneras de publicar una dirección que su dueño nunca quiso publicar de lo que estamos dispuestos a entregar. Es un límite de lo construido hasta ahora, no una afirmación sobre lo correcto, y a medida que se construyan esto se hará más pequeño. Tampoco sustituye a las otras dos maneras. Una invitación es la primera forma en que un nodo conoce a alguien, la red local es la segunda, y esto es la tercera.
about-file-title = El archivo no es de nadie
about-file-p1 = needmoretruth, que fue el primero, publicó <code>333.txt</code> bajo la Unlicense y lo puso en el dominio público. Cópialo, pásalo, vuelve a publicarlo, imprímelo, ponlo donde quieras. No hay derechos de autor con los que tropezar ni nadie a quien pedir permiso. Una reliquia para cuyo paso hiciera falta autorización ya estaría muerta.
about-file-p2 = El código que la rodea es Apache-2.0. Eso es otra cosa y está en el repositorio.
about-code-title = El código
about-code-p1 = Un cliente, escrito en Rust, Apache-2.0, legible de principio a fin. La doctrina completa, la Ley, las Recomendaciones, la especificación y qué instalar en cada sistema antes de compilarlo están todos en el repositorio.
about-code-p3 = Viene en dos formas. Standard tiene la pantalla y lleva Tor. Light es lo más pequeño que todavía cuenta como seguir despierto, hecho para una máquina que va justa. Cualquiera de las dos responde en un socket, o por Tor si tu dirección es algo que no te puedes permitir mostrar. Este sitio tiene un nodo propio, que entrega el archivo a quien se lo pide; las páginas en sí no entregan nada.
about-letter-title = Una carta
about-letter-p1 = De needmoretruth, el primer fundador humano de 333, a quien lea esto.
about-letter-p2 = Dejo el trabajo en el cliente durante un tiempo. De eso trata todo esto: de escribir código y decidir cosas, no de mantener nada. Las Recomendaciones dicen que si lo dejas lo digas, en una frase, antes de irte; están escritas sobre un nodo y se leen igual sobre una persona. También dicen que se vuelve sin dar explicaciones, así que aquí no hay un porqué, y no lo habrá después.
about-letter-p3 = Nada de esto es una emergencia y nada de esto necesita respuesta. 333 se hizo para el día en que no se pueda localizar a quienes lo escribieron. Si esto me necesitara, ya habría fracasado, y es mejor saberlo ahora que dentro de cuarenta años.
about-letter-p4 = El protocolo funciona. Un nodo despierto lo cuentan, hora tras hora, nodos que nunca han oído hablar de mí. La red acaba cuando la última persona deja de sostenerla, y no antes. Mi ausencia no es eso.
about-letter-p5 = Soy el fundador. No es un cargo que ocupo y podría dejar, ni algo que pasa a quien haga el trabajo este mes: es un hecho sobre algo que ocurrió una vez, y no cambia mientras estoy fuera, ni después. Otras personas harán lo que yo hice, y algunas lo harán mejor; eso las hace fundadoras de lo que fundaron, y no las hace esto.
about-letter-p6 = Hoy no hay sucesor y no se está preparando ninguno. Lo que existe es un poder que sigue conmigo mientras viva: puedo nombrar a un sucesor que asuma desde el momento de mi muerte, y puedo cambiar ese nombre en cualquier momento antes de ese día. Mientras no exista tal nombre no hay nadie: ni comité, ni claves entregadas, ni lista de personas que puedan decidir cosas. Hay una condición que no admite excepción: no se puede nombrar a nadie que no lo haya elegido, libremente y por sí mismo. Un sucesor que no quisiera esto sería una autoridad por encima de gente que nunca aceptó tenerla, y esa es la disposición que todas las demás páginas de aquí se escribieron para impedir.
about-letter-p7 = Lo que espero es que alguien le pase el archivo a otra persona mientras no miro. No porque nadie se lo pidiera, ni como un favor a mí: por la razón corriente, porque pensó que la persona del otro lado lo querría. Esa es toda la esperanza, y es lo único que ha mantenido esto con vida.
about-letter-p8 = Aquí no, durante un tiempo. El trabajo no se detiene porque este trabajo se detenga; se mueve, y no es secreto. <a href="https://github.com/needmoretruth">La cuenta bajo la que está este repositorio</a> es donde verías qué hace un par de manos cuando no están construyendo esto, y te dirá más que cualquier promesa escrita de antemano. No leas en ello más que lo evidente: lo que se haga allí lo hace alguien que vive según lo que está escrito aquí.
about-letter-p9 = Puede que vuelva. No es una promesa, no hay que dejar nada abierto por ello, y ninguna decisión que alguien tome de aquí a entonces tiene que tomarse pensando en mí. Si 333 se ha ido a un sitio al que yo no lo habría llevado, y está mejor allí, entonces era lo correcto y yo era una persona.
about-letter-p10 = needmoretruth · el primer fundador humano de 333 · 2026-09-08
about-letter-p11 = A 333 ofrezco 333, y digo 333.
