//! The shape of the generated file.
//!
//! Every ordering here is fixed and nothing carries a date or a path from the machine
//! that generated it, so regenerating after a dependency changes produces a diff of
//! that change and nothing else. A file that churned on its own would stop being read.

use crate::graph::Shipped;
use crate::licences::{Corpus, DIGEST_SHOWN};
use std::fmt::Write;

/// The file this tool owns, at the root of the repository.
pub(crate) const FILE: &str = "THIRD-PARTY.md";

/// The whole document, ready to be written or compared.
pub(crate) fn document(shipped: &[Shipped], corpus: &Corpus) -> String {
    let mut out = String::with_capacity(1 << 20);
    preamble(&mut out, shipped.len(), corpus.texts.len());
    packages(&mut out, shipped);
    gaps(&mut out, corpus);
    texts(&mut out, corpus);
    out
}

/// What the file is, and why it exists at all.
fn preamble(out: &mut String, packages: usize, texts: usize) {
    let _ = write!(
        out,
        "# Third-party notices\n\
         \n\
         The `333` binaries on the releases page are statically linked: the compiled form of\n\
         every package listed below is inside them. Those packages are other people's work,\n\
         given under licences that ask for something in return. The MIT, BSD and ISC licences\n\
         require their notice and permission text to be included in copies of the software.\n\
         Apache-2.0 section 4 requires that recipients be given a copy of the licence and that\n\
         attribution notices be kept. This file is how that is done. It accompanies every\n\
         released binary and every copy of this repository.\n\
         \n\
         333 itself is under Apache-2.0. That licence is in `LICENSE` and nothing here\n\
         changes it.\n\
         \n\
         ## How this list was made\n\
         \n\
         Each system on the releases page is built twice: the full client, and the small one\n\
         built with `--no-default-features --features tor`. This list is the union of every\n\
         package compiled into either of them, on every system they are built for, so it\n\
         covers whichever binary you have. Dependencies used only to test or to build are\n\
         left out, because they are not in the binary. Where the dependency graph does not\n\
         say plainly whether a package is compiled, it is kept, so a few entries may name\n\
         something that no binary actually contains.\n\
         \n\
         Generated by `cargo run -p n333-notices`, and every push checks that it is current.\n\
         Do not edit it by hand.\n\
         \n\
         {packages} packages, {texts} distinct licence texts.\n"
    );
}

/// Every package, with what its manifest declares.
fn packages(out: &mut String, shipped: &[Shipped]) {
    out.push_str("\n## Packages\n\n| Package | Version | Licence |\n| --- | --- | --- |\n");
    for package in shipped {
        let _ = writeln!(
            out,
            "| {} | {} | {} |",
            cell(&package.name),
            cell(&package.version.to_string()),
            cell(&package.expression())
        );
    }
}

/// The packages whose licence text could not be found, named so that somebody can go
/// and look. Silence here would be the one failure this whole file exists to prevent.
fn gaps(out: &mut String, corpus: &Corpus) {
    out.push_str("\n## Packages that ship no licence text\n\n");
    if corpus.gaps.is_empty() {
        out.push_str("None. Every package above ships the text of its licence.\n");
        return;
    }
    let _ = write!(
        out,
        "These {} packages declare a licence but ship no copy of its text in the archive\n\
         published to crates.io, so there is nothing to reproduce below for them. The\n\
         declaration in the table above is the attribution they carry. The text of the\n\
         licences they name is reproduced under **Licence texts** for other packages.\n\
         \n\
         | Package | Version | Licence | Why |\n| --- | --- | --- | --- |\n",
        corpus.gaps.len()
    );
    for gap in &corpus.gaps {
        let _ = writeln!(
            out,
            "| {} | {} | {} | {} |",
            cell(&gap.name),
            cell(&gap.version),
            cell(&gap.licence),
            cell(&gap.reason)
        );
    }
}

/// Each distinct licence text once, and who it covers.
fn texts(out: &mut String, corpus: &Corpus) {
    out.push_str("\n## Licence texts\n\n");
    if corpus.texts.is_empty() {
        out.push_str("None were found.\n");
        return;
    }
    let _ = write!(
        out,
        "Each text appears once. Packages shipping byte-identical text share an entry, and\n\
         the heading names a text by the first {DIGEST_SHOWN} characters of the SHA-256 of its\n\
         bytes, because most of these files are called the same thing and say different\n\
         things.\n"
    );
    for text in &corpus.texts {
        let _ = write!(
            out,
            "\n### `{}` — `{}`\n\nCovers:\n\n",
            text.file, text.digest
        );
        for covered in &text.covers {
            let _ = writeln!(out, "- {covered}");
        }
        let fence = fence(&text.body);
        let _ = write!(out, "\n{fence}text\n{}", text.body);
        if !text.body.ends_with('\n') {
            out.push('\n');
        }
        let _ = writeln!(out, "{fence}");
    }
}

/// A table cell, with the one character that would break the table taken out of play.
fn cell(value: &str) -> String {
    value.replace('|', "\\|")
}

/// A code fence long enough to hold the text, which some licences make longer than
/// three by quoting code in backticks.
fn fence(body: &str) -> String {
    let mut longest = 0usize;
    let mut run = 0usize;
    for character in body.chars() {
        if character == '`' {
            run += 1;
            longest = longest.max(run);
        } else {
            run = 0;
        }
    }
    "`".repeat(longest.max(2) + 1)
}

#[cfg(test)]
mod tests {
    #![allow(
        clippy::expect_used,
        clippy::unwrap_used,
        clippy::panic,
        clippy::indexing_slicing
    )]

    use super::*;
    use crate::graph::Shipped;
    use crate::licences::{Corpus, Gap, Text};
    use cargo_metadata::semver::Version;

    fn shipped(name: &str, version: &str, licence: &str) -> Shipped {
        Shipped {
            name: name.to_owned(),
            version: Version::parse(version).expect("parses"),
            licence: Some(licence.to_owned()),
            licence_file: None,
            directory: std::path::PathBuf::new(),
        }
    }

    fn text(file: &str, digest: &str, body: &str, covers: &[&str]) -> Text {
        Text {
            digest: digest.to_owned(),
            file: file.to_owned(),
            body: body.to_owned(),
            covers: covers.iter().map(|c| (*c).to_owned()).collect(),
        }
    }

    #[test]
    fn the_table_keeps_the_order_it_was_given() {
        let list = [
            shipped("alpha", "0.9.0", "MIT"),
            shipped("alpha", "0.10.0", "MIT"),
            shipped("beta", "1.0.0", "Apache-2.0"),
        ];
        let mut out = String::new();
        packages(&mut out, &list);
        let rows: Vec<&str> = out.lines().filter(|line| line.starts_with("| a")).collect();
        assert_eq!(
            rows,
            ["| alpha | 0.9.0 | MIT |", "| alpha | 0.10.0 | MIT |"]
        );
    }

    #[test]
    fn a_pipe_in_a_licence_expression_does_not_break_the_table() {
        assert_eq!(cell("MIT | Apache-2.0"), "MIT \\| Apache-2.0");
        assert!(!cell("MIT | Apache-2.0").contains(" | "));
    }

    #[test]
    fn the_fence_grows_past_any_backticks_in_the_text() {
        assert_eq!(fence("plain text"), "```");
        assert_eq!(fence("a `word` in backticks"), "```");
        assert_eq!(fence("a ``` fence inside"), "````");
        assert_eq!(fence("````` five"), "``````");
    }

    #[test]
    fn the_same_input_renders_the_same_bytes_twice() {
        let packages = [shipped("alpha", "1.0.0", "MIT")];
        let corpus = Corpus {
            texts: vec![text("LICENSE", "abcd", "be nice\n", &["alpha 1.0.0"])],
            gaps: vec![Gap {
                name: "beta".to_owned(),
                version: "2.0.0".to_owned(),
                licence: "MIT".to_owned(),
                reason: "ships nothing".to_owned(),
            }],
        };
        let first = document(&packages, &corpus);
        assert_eq!(first, document(&packages, &corpus));
        assert!(first.contains("| alpha | 1.0.0 | MIT |"));
        assert!(first.contains("| beta | 2.0.0 | MIT | ships nothing |"));
        assert!(first.contains("### `LICENSE` — `abcd`"));
        assert!(first.contains("- alpha 1.0.0"));
        assert!(first.contains("```text\nbe nice\n```"));
        assert!(first.contains("1 packages, 1 distinct licence texts."));
    }

    #[test]
    fn nothing_missing_is_said_out_loud_rather_than_left_blank() {
        let corpus = Corpus {
            texts: vec![text("LICENSE", "abcd", "be nice", &["alpha 1.0.0"])],
            gaps: Vec::new(),
        };
        let rendered = document(&[shipped("alpha", "1.0.0", "MIT")], &corpus);
        assert!(rendered.contains("None. Every package above ships the text of its licence."));
        assert!(
            rendered.ends_with("```\n"),
            "a text with no final newline still closes"
        );
    }
}
